# Generated by Django 3.0.6 on 2020-06-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenthistory',
            old_name='type',
            new_name='history_type',
        ),
    ]
