# Generated by Django 3.0.6 on 2020-06-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0002_auto_20200620_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthistory',
            name='value',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
