# Generated by Django 3.0.6 on 2020-06-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0003_studenthistory_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursestudents',
            old_name='student',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='studenthistory',
            old_name='student',
            new_name='user',
        ),
    ]
