# Generated by Django 3.0.6 on 2020-06-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0004_auto_20200620_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='history_type',
            field=models.CharField(choices=[(0, 'sugar'), (1, 'pressure'), (2, 'height'), (3, 'weight'), (4, 'foodsleep'), (5, 'watter'), (6, 'coffee'), (7, 'tea'), (8, 'running'), (9, 'cycling'), (10, 'swimming'), (11, 'hiking'), (12, 'walking'), (13, 'dancing')], default='1', max_length=9),
        ),
    ]
