# Generated by Django 3.0.6 on 2020-07-02 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0005_auto_20200622_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
